### PR TITLE
fix: Throttling=0 is not working when posting a subscription

### PR DESCRIPTION
**Pull request by tstorek**
@StWiemann I added this code snippet. Please have a look if this works fine for you!
It would be great if you could write a quick test for it!

For #148

### CODE REVIEW

**Comment by StWiemann** [comment]
Hi @tstorek, 
sorry that I didn't get around to push the proposed PR last week. This looks almost identical to what I've done and works just fine! Thank you.

**Comment by tstorek** [comment]
@StWiemann would you be so kind to write a test for this?

**Comment by StWiemann** [comment]
@tstorek Yes, would you like me to add this to clients -> `class TestTimeSeries` in the `test_ngsi_v2_timeseries.py` ?

**Comment by tstorek** [comment]
@StWiemann sounds good to me. Simply use my branch for it. Please

**Comment by djs0109** [comment]
I don't know, if you also notice the returned message from QL: `This API is deprecated, it will be removed in version 0.9`. It seems like this kind of request will no longer be possible in the future.

**Comment by tstorek** [comment]
@djs0109 good point. I will move the test to the contextbroker ;) same same :)

**Review by djs0109 — APPROVED** [review]

**Pull request merged**
