### PR TITLE
Adding new attributes to the HttpCustom model 

### PR DESCRIPTION
**Pull request by RCX112**
Extended the pydantic model with the attributes json, ngsi and timeout. Also added some tests for the pydantic model.

### CODE REVIEW

**Comment by djs0109** [comment]
@RCX112 I think there might be some misunderstanding. The issue #290 should actually add `headers` under `httpCustom`. The related docs are [here](https://fiware-orion.readthedocs.io/en/3.8.0/orion-api.html#custom-notifications)

**Comment by djs0109** [comment]
OK, I get it now. The `headers` already exists

**Comment by djs0109** [comment]
@RCX112 I will then merge #290  to #288 and then close the #290 . What do you think?

**Comment by RCX112** [comment]
@djs0109 Sorry for the misunderstanding, we discussed this problem also in yesterday's meeting. I think merging both branches is a good idea

**Comment by djs0109** [comment]
Close, because it is merged to #288

**Pull request closed without merging**
